<?php
namespace Seddkit;

/**
 * class for one tainted string
 */
class TaintedScalar extends Tainted
{
    /**
     * @var boolean True if the inputs is instanciate but not expected 
     */
    protected $autogenerated = false;
    
	/**
	 * Clean string returned if safety test fail
	 * @var string
	 */
	protected $default_data = NULL;

	/**
	 * String that is tainted
	 * @var mixed
	 */
	protected $data;

    protected $bypass = array();
    protected $preventTrim = false; 

    
	/**
	 * Constructor of the class.
     * If empty, $data should be set to 'null' in order to keep the same behaviors with empty()
     *
	 * @param string $data		The string that is to be tainted
     * @param default_data      The default value if $data value is empty
	 */
	public function __construct($data, $varname_str=null)
	{
        $this->_varname = $varname_str;
        
		$this->data = $data;
        // todo : default ?
		$this->default_data = null;
	}
    
    public function bypass2string($reason_str)
    {
        $this->bypass["".microtime()] = $reason_str;
        
        if($this->data == null)
			return $this->default_data;
		else 
			return $this->data;
    }

    
	/**
	 * Function to trigger error when trying to use a string that is tainted
	 * @return string	The string that is tainted
	 */
	public function __toString()
	{
		if(Seddkit::CONFIG('TAINT_CHECKING') and $this->isTainted())	//If the string is tainted, then trigger the error
			throw new DevelopmentSecurityException($this,'TAINT_CHECKING');
		
		return bypass2string();
	}
	
	/**
	 * Function to trigger error when trying to use a string that is tainted
	 * @return string	The string that is tainted
	 */
	public function __sleep()
	{
		if(Seddkit::CONFIG('TAINT_CHECKING') and $this->isTainted())	//If the string is tainted, then trigger the error
			throw new DevelopmentSecurityException($this,'TAINT_CHECKING');
		
		return bypass2string();
	}
    
	/**
	 * To prevent trim() when data is sanitized
	 * Chainable
	 * 
	 * @method TaintedString preventTrim()
	 * @return TaintedString 
	 */
	public function preventTrim()
	{
	    $this->preventTrim = true;
	    
	    return $this;
	}

	/*
	public function sanitizeWithCheck()
	{
	    $args = func_get_args();
	    $method = array_shift($args);
	    
	    $this->data = ($this->preventTrim == false)? trim($this->data) : $this->data ;
	    
	    array_unshift($args, $this->data);
	     
	    if( is_callable('\Ufo\Security\Check::'.$method)){
	        
	        if( call_user_func_array('\Ufo\Security\Check::'.$method, $args)){
	            $this->decontaminate();
	        }
	        else{            
	            $this->data = $this->default_data;
	            $this->decontaminate();
	        }
	        
	        return $this->data;
	    }
	    else{
	        throw new TaintedSanitizerErrorExcetion();
	        return null;
	    }
	}
	
	/**
	 * 
	 * @param unknown $data_mixed
	 */
	public function setDefault( $data_mixed)
	{
		$this->default_data = $data_mixed;
		
		return $this;
	}
	
	
	/**
	 * Chainable
	 */
	public function markAsAutogenerated()
	{
	   $this->autogenerated = true;   
	   
	   return $this;
	}
	
	/**
	 * 
	 */
	public function isAutogenerated()
	{
        return $this->autogenerated;
	}

	/**
	 * 
	 * @return number
	 */
    public function length()
    {
        $this->data = ($this->preventTrim == false)? trim($this->data) : $this->data ;
        
        return strlen($this->data);
    }
    
    public function getDefaultData()
    {
        return $this->default_data;
    }
    
    public function getData(){ return $this->data; }
}
?>